### ISSUE TITLE
DNS test cannot resolve name

### ISSUE THREAD

**Issue by tdiesler** [ipfs/java-ipfs-http-client#103] opened 2018-09-04 10:03 UTC
```
Tests run: 37, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 70.75 sec <<< FAILURE! - in io.ipfs.api.APITest
dnsTest(io.ipfs.api.APITest)  Time elapsed: 0.166 sec  <<< ERROR!
java.lang.RuntimeException: 
IOException contacting IPFS daemon.
Trailer: [X-Stream-Error] {"Message":"could not resolve name (recursion limit exceeded)","Code":0,"Type":"error"}

	at io.ipfs.api.APITest.dnsTest(APITest.java:623)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://127.0.0.1:5001/api/v0/dns?arg=ipfs.io
	at io.ipfs.api.APITest.dnsTest(APITest.java:623)
```

**Comment by magik6k** [comment] 2018-09-05 16:30
This is caused by infra change which broke similar test in js-ipfs-api - https://github.com/ipfs/js-ipfs-api/issues/839. TL;DR is that you need to call `resolve` with `-r` to resolve ipfs.io now.

**Comment by ianopolous** [comment] 2018-12-21 00:02
This is fixed in master now

**Closed by ianopolous** 2018-12-21 00:02 UTC
